on:
  push:
    branches:
      - android
  pull_request:
    branches:
      - android
name: Build Debug APK
jobs:
  main:
    name: base
    strategy:
      matrix:
        os:
          - ubuntu-latest
        architecture:
          - x64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Build debug APK
        run: |
          mkdir ~/.buildozer
          docker pull kivy/buildozer
          docker run --volume "$HOME/.buildozer":/home/user/.buildozer --volume "$PWD":/home/user/hostcwd kivy/buildozer android debug

      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: Debug APK
          path: bin